### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by taegrr** [teijo/jquery-group#6]
I see you haven't updated this in 4 years? Why is that? The brackets works like a charm. But this one seems to have a lot of issues, any chance of an update at any point soon?

I help run a tournament that uses both a round-robin group stage followed by a bracketed stage. So it would be great to be able to use both (also with more updated versions of the libraries)

**Comment by teijo** [comment]
Hi,

The project has been on background once the prototype was completed. As you can see from the issues tab, there hasn't been too much feedback from the community regarding how it works. It's been on my todo list to modernize this project too, so perhaps I'll take a look at it again this weekend.

If you have specific bugs in mind, feel free to point them out in separate issues.
